import type { Survey } from '../src/types';

export const satisfactionSurvey: Survey = {
  meta: {
    id: 'satisfaction_001',
    title: '产品使用满意度调研',
    description:
      '感谢您使用我们的产品！请花几分钟时间完成以下问卷，您的反馈将帮助我们不断改进和优化产品体验。所有信息将严格保密。',
    version: '1.0.0',
    createdAt: '2025-01-15',
    updatedAt: '2025-06-10',
  },
  questions: [
    {
      id: 'q_department',
      type: 'single',
      title: '您所在的部门是？',
      required: true,
      order: 1,
      options: [
        { id: 'dept_1', label: '研发部', value: 'rd' },
        { id: 'dept_2', label: '产品部', value: 'pm' },
        { id: 'dept_3', label: '设计部', value: 'design' },
        { id: 'dept_4', label: '市场部', value: 'marketing' },
        { id: 'dept_5', label: '销售部', value: 'sales' },
        { id: 'dept_6', label: '运营部', value: 'ops' },
        { id: 'dept_7', label: '其他', value: 'other' },
      ],
    },
    {
      id: 'q_usage_freq',
      type: 'single',
      title: '您使用本产品的频率是？',
      required: true,
      order: 2,
      options: [
        { id: 'freq_1', label: '每天使用', value: 'daily' },
        { id: 'freq_2', label: '每周多次', value: 'weekly_multi' },
        { id: 'freq_3', label: '每周1-2次', value: 'weekly' },
        { id: 'freq_4', label: '每月几次', value: 'monthly' },
        { id: 'freq_5', label: '很少使用', value: 'rarely' },
      ],
    },
    {
      id: 'q_usability',
      type: 'rating',
      title: '产品易用性评分',
      description: '1分表示非常难用，5分表示非常好用',
      required: true,
      order: 3,
      minValue: 1,
      maxValue: 5,
      step: 1,
      labels: [
        { value: 1, label: '非常难用' },
        { value: 2, label: '较难用' },
        { value: 3, label: '一般' },
        { value: 4, label: '较易用' },
        { value: 5, label: '非常易用' },
      ],
    },
    {
      id: 'q_usability_detail',
      type: 'text',
      title: '请详细说明您给出该评分的原因',
      description: '例如：哪些功能方便使用？哪些操作比较复杂？',
      required: false,
      order: 4,
      placeholder: '请输入您的反馈...',
      multiline: true,
      maxLength: 500,
      skipLogic: [
        {
          conditions: [
            {
              questionId: 'q_usability',
              operator: 'lte',
              value: 3,
            },
          ],
          logic: 'AND',
          targetQuestionId: 'q_performance',
        },
      ],
    },
    {
      id: 'q_features',
      type: 'multiple',
      title: '您最常用的功能有哪些？',
      description: '可多选，最少选择1项，最多选择5项',
      required: true,
      order: 5,
      minSelect: 1,
      maxSelect: 5,
      options: [
        { id: 'feat_1', label: '数据分析与报表', value: 'analytics' },
        { id: 'feat_2', label: '团队协作', value: 'collab' },
        { id: 'feat_3', label: '文档管理', value: 'docs' },
        { id: 'feat_4', label: '消息通知', value: 'notify' },
        { id: 'feat_5', label: '权限管理', value: 'perms' },
        { id: 'feat_6', label: 'API集成', value: 'api' },
        { id: 'feat_7', label: '移动端支持', value: 'mobile' },
      ],
    },
    {
      id: 'q_performance',
      type: 'rating',
      title: '系统性能与稳定性评分',
      description: '包括页面加载速度、响应时间、崩溃率等',
      required: true,
      order: 6,
      minValue: 1,
      maxValue: 10,
      step: 1,
      labels: [
        { value: 1, label: '极差' },
        { value: 5, label: '中等' },
        { value: 10, label: '极佳' },
      ],
    },
    {
      id: 'q_support',
      type: 'rating',
      title: '客户服务与技术支持满意度',
      required: true,
      order: 7,
      minValue: 1,
      maxValue: 5,
      labels: [
        { value: 1, label: '非常不满意' },
        { value: 3, label: '一般' },
        { value: 5, label: '非常满意' },
      ],
    },
    {
      id: 'q_overall',
      type: 'rating',
      title: '整体满意度评分',
      required: true,
      order: 8,
      minValue: 0,
      maxValue: 10,
      labels: [
        { value: 0, label: '完全不满意' },
        { value: 10, label: '完全满意' },
      ],
    },
    {
      id: 'q_recommend',
      type: 'single',
      title: '您是否会向同事或朋友推荐本产品？',
      required: true,
      order: 9,
      options: [
        { id: 'rec_1', label: '一定会推荐', value: 'definitely' },
        { id: 'rec_2', label: '可能会推荐', value: 'maybe' },
        { id: 'rec_3', label: '不确定', value: 'not_sure' },
        { id: 'rec_4', label: '不太可能推荐', value: 'unlikely' },
        { id: 'rec_5', label: '一定不会推荐', value: 'never' },
      ],
    },
    {
      id: 'q_comments',
      type: 'text',
      title: '其他建议或意见',
      description: '如果您有任何其他想说的，请告诉我们',
      required: false,
      order: 10,
      placeholder: '请输入您的宝贵建议...',
      multiline: true,
      maxLength: 1000,
    },
  ],
};
